# Generated by Django 4.2.5 on 2023-09-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_number', models.IntegerField(max_length=10)),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_location', models.CharField(max_length=100)),
                ('emp_salary', models.FloatField(default=10)),
            ],
        ),
    ]
