# Generated by Django 4.2.5 on 2023-09-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('select_reletedapp', '0004_reader_story'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='writer',
        ),
        migrations.AddField(
            model_name='story',
            name='reader',
            field=models.ManyToManyField(to='select_reletedapp.reader'),
        ),
    ]
