# Generated by Django 4.2.5 on 2023-09-24 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fieldsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fieldsapp.address'),
        ),
    ]
