# Generated by Django 4.2.5 on 2023-10-06 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("studentapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="studentapp.city",
            ),
        ),
    ]
