# Generated by Django 4.2.5 on 2023-09-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=24)),
                ('bio', models.CharField(max_length=240)),
                ('email', models.CharField(max_length=24)),
                ('phone', models.IntegerField(max_length=24)),
            ],
        ),
    ]
