# Generated by Django 4.2.5 on 2023-09-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajax1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
