# Generated by Django 4.2.5 on 2023-10-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokenapi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bike",
            name="is_avalible",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
