# Generated by Django 4.2.5 on 2023-10-12 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerceapi", "0002_productcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category_name",
            field=models.ForeignKey(
                db_column="category_name",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ProductCategory",
                to="ecommerceapi.productcategory",
            ),
        ),
    ]
