# Generated by Django 4.2.5 on 2023-09-28 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiformapp', '0002_alter_studentinfo_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='created_by',
        ),
    ]
