# Generated by Django 4.2.5 on 2023-10-13 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmployeeDept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_dept_id", models.PositiveIntegerField()),
                ("employee_dept", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.PositiveIntegerField()),
                ("employee_name", models.CharField(max_length=100)),
                ("employee_email", models.EmailField(max_length=254)),
                ("employee_location", models.CharField(max_length=100)),
                (
                    "employee_dept",
                    models.ForeignKey(
                        db_column="employee_dept",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="EmployeeDept",
                        to="mixinsapi.employeedept",
                    ),
                ),
            ],
        ),
    ]
