# Generated by Django 4.2.5 on 2023-10-01 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Collage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.IntegerField()),
                ('data_of_birth', models.DateField()),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dropdownlist.branch')),
                ('collage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dropdownlist.collage')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='collage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dropdownlist.collage'),
        ),
    ]
