# Generated by Django 4.2.5 on 2023-10-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StrangersThings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actors_name", models.CharField(max_length=100)),
                ("actor_charactor_name", models.CharField(max_length=100)),
                ("actress_name", models.CharField(max_length=100)),
                ("actress_charactor_name", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
    ]
